language: node_js
node_js:
  - 14
script:
  - npm run test
  - chmod a+x ./publish-npm.sh
  - ./publish-npm.sh
deploy:
  provider: npm
  email: "$NPM_AUTH_USER"
  api_key: "$NPM_AUTH_TOKEN"
  on:
    tags: true
    branch: master
