language: node_js
node_js:
- 14
script:
- npm run test
- chmod a+x ./publish-npm.sh
- npm run build

before_deploy:
  - npm run test
  - npm run build
deploy:
  provider: npm
  email: "$NPM_AUTH_EMAIL"
  user: "$NPM_AUTH_USER"
  api_key:
    secure: Ga6lZ5RTKDwOrB5EvJQ2kMx4zDxOUXkDx+9NkfypTTRShDpg6ebkDDmWa6aKI4RzKNx9IynWzqYbOx7sMttV3FgpJFx1aBW4npxRSs2dHe0of7ksYkrK8c5Ywdybb1fCFG3ooHckMpoetX6BVoPGeCn+EoQUndW/UILhgMgZWAOpyRpIHxTQ/qIMao0ny7qY4KmyoHkhWC5ZqQGNpnRilCju9dYVzr7dEtBfwZf0+flsQR3DRsiEsFhDz+sdeNzUYQwJsxUuzADBYpCrFvZBOSWqcuJ8bsuT5v260wC3NoxfKj6ULgJIqlmagJeTnd4yH38GLCnthW5syuivBmxX7Ir1G5OX1YurK0vO9cSP0Ix61tg319SZpPsmS1cb8SdPfaVkE6UbJmfEzEU8u41rP0/JxmN75E6wzviAjbz1jLMvqWjXc9uvJr53RDUz17ElBGSFio6ZH3d/0K0oJ5V0X755vxVlp+mwrto9PgcJfxTyfwlYmxk2WobCDK46RCEt2RfCpqXFUCEIyN5ZInnejCCilwntJromGpkFhTqEHEfTe5llIXMZDwyoVLYMH5AyqQ1vzKZLaA/RCP0YsHqcShK6ZU+wjiIonY563GuPyRDWLqQ97bqYe8bz3RI5lQB21PESeTNWmDaAuyJekTKnai+Y1qukCp203xFEcLpTMcg=
  on:
    tags: true
    branch: master
